[project]
name = "micromanager"
version = "0.1.0"
description = "CLI application to manage microservices with docker-compose"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "compose-py>=0.3.0",
    "docker-composer>=2.79.7",
    "typer>=0.16.0",
]
