[project]
name = "micromanager"
version = "0.1.0"
description = "CLI application to manage microservices with docker-compose"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "compose-py>=0.3.0",
    "docker-composer>=2.79.7",
    "platformdirs>=4.3.8",
    "typer>=0.16.0",
]

[dependency-groups]
dev = [
    "ty>=0.0.1a14",
    "unittest-extensions>=0.4.0",
]
